# Generated by Django 4.2.20 on 2025-03-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.IntegerField()),
                ('terminal', models.CharField(default='Kabayan', max_length=30)),
                ('destination', models.CharField(default='Baguio', max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
            ],
        ),
    ]
