# Generated by Django 4.2.20 on 2025-03-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='terminal',
            new_name='origin',
        ),
    ]
