# Generated by Django 4.2.20 on 2025-03-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
