# Generated by Django 4.2.20 on 2025-03-15 15:42

from django.db import migrations, models


def populate_trip_id(apps, schema_editor):
    Trip = apps.get_model('reservation', 'Trip')
    for trip in Trip.objects.all():
        trip.trip_id = trip.pk
        trip.save()

class Migration(migrations.Migration):
    dependencies = [
        ('reservation', '0002_alter_trip_date_alter_trip_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_id',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(populate_trip_id),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.IntegerField(null=False),
        )
    ]
    
