# Generated by Django 4.2.20 on 2025-03-15 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0003_auto_20250315_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='id',
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_number',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_trip', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
