# Generated by Django 5.1.7 on 2025-03-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_trip_id_alter_trip_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='selected_trip',
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
    ]
