# Generated by Django 5.1.7 on 2025-03-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_reservation_selected_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_number',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
